<!-- JS here -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
{{-- <script src="/assets-shop/js/vendor/jquery-3.5.0.min.js"></script>
<script src="/assets-shop/js/popper.min.js"></script>
<script src="/assets-shop/js/bootstrap.min.js"></script> --}}
<script src="/assets-shop/js/isotope.pkgd.min.js"></script>
<script src="/assets-shop/js/imagesloaded.pkgd.min.js"></script>
<script src="/assets-shop/js/jquery.magnific-popup.min.js"></script>
<script src="/assets-shop/js/owl.carousel.min.js"></script>
<script src="/assets-shop/js/jquery.odometer.min.js"></script>
<script src="/assets-shop/js/jquery.countdown.min.js"></script>
<script src="/assets-shop/js/jquery.appear.js"></script>
<script src="/assets-shop/js/slick.min.js"></script>
<script src="/assets-shop/js/ajax-form.js"></script>
<script src="/assets-shop/js/wow.min.js"></script>
<script src="/assets-shop/js/aos.js"></script>
<script src="/assets-shop/js/plugins.js"></script>
<script src="/assets-shop/js/main.js"></script>
<script src="js/frontend.js"></script>
